### ISSUE TITLE
Magical Github Integration w/o information?

### ISSUE THREAD

**Issue by bradennapier** [atom/github#1029]
is there information anywhere about how to make the github stuff work?  From what I can see it makes me create a brand new project and start over rather than simply taking the project I am using and using the .git file there to build the git integration?  

Should have some information about how to set it up and if you have to start a new project for some reason then you should put that somewhere. 

Only option I have found thus far is create new repository / project so sorry if I am missing something!

**Comment by goodroot** [comment]
@bradennapier Did you get this working? This integration appeared within Atom this morning; It doesn't connect to anything, even the repos it creates. Not sure what to do.

**Comment by rsese** [comment]
For the GitHub part of the package to work, you need use a repository with a remote pointing to an existing GitHub repository.  Then you should be prompted to login with an auth token.

@bradennapier @goodroot - can either of you confirm if you're working with GitHub repository and if so, can you share what you're seeing in the GitHub tab?

---

As a side note, filling out the issue template is super helpful for us since it lets us know if you'd tried in safe mode, what version of Atom you're running, what operating you're on, etc.

**Comment by goodroot** [comment]
Ah, yeah, sorry about the template -- wanted to see if Braden found something out, in case we were both doing something silly.

I can confirm I am working within a GitHub directory; my GitHub folder is my project within Atom. The GitHub folder is created by the GitHub desktop app. Here are two images, one in safe-mode and one in regular-mode.

![screen shot 2560-07-20 at 6 32 04 pm](https://user-images.githubusercontent.com/9484709/28445579-057212e6-6d7a-11e7-8897-4333bb3c43b6.png)
![screen shot 2560-07-20 at 6 32 29 pm](https://user-images.githubusercontent.com/9484709/28445580-0576b882-6d7a-11e7-8ff8-8573ef4e8101.png)

The panes are gray'd out; the config files show happy and connected config files.

**Comment by 50Wliu** [comment]
Ah, I think I see your problem @goodroot.  The `GitHub` folder itself is not a Git repository - in order for GitHub integration to show up, the root folder has to be a Git repository.  So in your case try opening `goodroot.ca` as a new project.

**Comment by goodroot** [comment]
Hot dog! You're on the money, @50Wliu -- thanks for the suggestion.

It's working well. Ahh, this feature excites me. Farewell, desktop app. 👍  <3
