### ISSUE TITLE
Not quite understanding how atom and Github work together...initial configuration

### ISSUE THREAD

**Issue by arretx** [atom/github#1190]
I'm completely new to Github, but I understand the concept.  I am also new to Atom, but it seems relatively straightforward, except for the problem I'm having.

I'm working with Home-Assistant.io.  It's installed in a hidden folder .homeassistant.

Atom sees this folder and it is a project folder now in Atom.  Git is installed, and I seem to have a connection to Github through Atom for a completely new project.

What I'm unclear about is this.

Since I started with Github AFTER I started with HASS, how do I mirror the homeassistant folder to my GitHub repository through Atom?  Configuration is very confusing.  So far I've only been able to create a NEW repository and then use the clone URL to get Atom to see it, but it's for a different folder on my local machine.

Atom 1.20.1
MacBook High Sierra
Home Assistant 0.53.1

Thanks in advance.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

> how do I mirror the homeassistant folder to my GitHub repository through Atom?

You can fetch, push and pull by clicking the arrows in the status bar:

![image](https://user-images.githubusercontent.com/1058982/30795241-e953cb5e-a1cc-11e7-914c-5ff436ba776c.png)

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
