### ISSUE TITLE
Require confirmation on undo discard

### ISSUE THREAD

**Issue by steelbrain** [atom/github#1260]
### Description

The package should confirm the user if they really want to undo discarded changes. There's no spacing between that button and the first diff item so I accidentally press it often and have to manually search through the diff to see what it restored and undo that
### Versions

```
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.2
```
Using bundled v0.7.0 of this package

**Comment by consideRatio** [comment]
It just happened to me the second time, and it messed up things big time. Somewhere in the code I just introduced a bug... Where? Hard to tell...

**Comment by kuychaco** [comment]
Hey folks thanks for the feedback! In #1702 we moved the button behind a menu in the header. It's now much harder to accidentally undo the last discard. 

It's still a valid request to prompt for confirmation before undoing. I'll open up a separate issue to discuss this (specifically if head has moved since the last discard). I closed this issue because it refers to a UX that is obsolete after this change.

**Comment by kuychaco** [comment]
Actually, I'm curious to first ask if confirmation would still be desirable given the new UX. And if so, is it desirable to prompt every time? Would that be annoying or intrusive sometimes?

**Comment by Aerijo** [comment]
@kuychaco 
>  is it desirable to prompt every time? 

If there's to be a prompt, I would say an always on prompt is good, with an option to disable future prompts. That way you let the user decide for themselves.

**Comment by KiGniark** [comment]
The prompt won't be necessary in my opinion. If a mistake occurs, i'd prefer a redo button in that menu instead of a prompt.
About prompts, it tends to interrupt a workflow by asking something but if you have a way to revert it feels more like a flow. Prompts shouldn't be on something that could be used often.
Example: Someone discards a lot of change, he should be able to undo/redo at will. If you prompts at him for every undo/redo he tries, he'll just get mad at Atom.
