### ISSUE TITLE
Issue Publishing Plugin

### ISSUE THREAD

**Issue by daylerees** [atom/github#1280]
Hi guys,

I'm struggling to publish my plugin (https://github.com/rainglow/atom) using apm, here's the output.

```
~/P/r/atom ❯❯❯ apm publish patch
Welcome to Atom!

Before you can publish packages, you'll need an API token.

Visit your account page on Atom.io https://atom.io/account,
copy the token and paste it below when prompted.

Press [Enter] to open your account page on Atom.io.
Token> _pe_0I---CENSORED---Btw
Saving token to Keychain ✓
(node:65871) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: The user name or passphrase you entered is not correct.
Preparing and tagging a new version ✓
Pushing v1.5.5 tag Username for 'https://github.com': daylerees
Password for 'https://daylerees@github.com':
✗
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/rainglow/atom/'
```

I've confirmed the username and password are correct, and the token despite censored in the above  is exactly as stated on the site.

Could it be something to do with it being an org or maybe 2FA?

Thanks for your help,
Dayle.

**Comment by rsese** [comment]
If you're using 2FA with your user account, try using a personal access token instead of your password:

https://help.github.com/articles/providing-your-2fa-authentication-code/#when-youll-be-asked-for-a-personal-access-token-as-a-password

If that still doesn't help, go ahead and open an issue in https://github.com/atom/apm so we have it in the right place and we can go from there.
