### ISSUE TITLE
Are you planning to add side-by-side git diff?

### ISSUE THREAD

**Issue by borishere** [atom/github#1423]

**Comment by rsese** [comment]
Thanks for reaching out!  https://github.com/atom/github/issues/816 was opened to capture this request but we can't make any promises about if or when a particular feature might be implemented - you can subscribe there for updates if you'd like however.

About the team's plans and what they're working on for the GitHub package in general, this is best described at https://github.com/atom/github/tree/master/docs/vision#so-when-are-you-building-all-this-stuff-then.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by simurai** [comment]
There is a PR #866, but a bit out of date.

@borishere You might can try this community package: https://atom.io/packages/split-diff
