### ISSUE TITLE
Files are not case sensitive

### ISSUE THREAD

**Issue by linjialiang** [atom/github#1468]
> `windows 10` Files are not case sensitive
> 
![default](https://user-images.githubusercontent.com/8848263/40182987-3c3f5ba2-5a1f-11e8-9759-86239e74c734.png)

**Comment by rsese** [comment]
Thanks for reaching out!  

If you can share more information about the issue you're having, we can take a look.  For example, can you describe the issue in more detail and provide step by step instructions to reproduce the behavior?  If you can provide more information, we can re-open and go from there.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by linjialiang** [comment]
The question I raised in #1474  can be solved.
> Question mean, roughly in ` atom ` can not switch normal branch!If you switch branches, files that have been altered may be lost.
