### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1573]
I'd like to start a conversation about possible ways that we can improve discoverability of the git and GitHub features in Atom.

This is what we have in place presently:

(1) The welcome package includes buttons to open the Git and GitHub tabs, and a nudge referencing the status bar tile:

<img width="300" alt="screen shot 2018-07-10 at 8 14 54 am" src="https://user-images.githubusercontent.com/17565/42509293-732a2650-8419-11e8-81a9-6d90c71a4e1f.png">

(2) The hints that cycle when no panes are open in the workspace center includes mentions of the keyboard shortcuts:

<img width="300" alt="screen shot 2018-07-10 at 8 17 33 am" src="https://user-images.githubusercontent.com/17565/42509414-c59fa400-8419-11e8-9df3-f0a157385391.png">

(3) The status bar tiles themselves are always visible:

<img width="300" alt="screen shot 2018-07-10 at 8 18 33 am" src="https://user-images.githubusercontent.com/17565/42509453-e3adf0aa-8419-11e8-946a-11eb4f68ed77.png">

(4) The package's initial state. The first time that Atom is opened with the GitHub package installed, if the Welcome package is not shown, the right dock is opened with the Git and GitHub tabs present. Each time a new project is initialized, the Git and GitHub tabs are opened in the right dock but the right dock itself is not expanded.

(5) The "Packages" menu includes a "GitHub" entry, with the keyboard shortcuts listed:

<img width="300" alt="screen shot 2018-07-10 at 8 28 56 am" src="https://user-images.githubusercontent.com/17565/42509916-5e738d94-841b-11e8-915c-7cde411afbef.png">

But our feeling is that these are not sufficient:

[<img width="678" alt="screen shot 2018-07-10 at 8 22 21 am" src="https://user-images.githubusercontent.com/17565/42509624-876f585a-841a-11e8-9921-559e3959becd.png">](https://twitter.com/rauschma/status/1007103720830783489)

The GitHub tab is even more hidden: you have to know about the keyboard shortcut or the command palette entry to get to it.

Soon, thanks to @annthurium, we'll have access to metrics that we can use to validate this hypothesis, and measure the impact of any changes that we make to improve this 😁 Before we even have a baseline, though, I'd :heart: to start collecting ideas and brainstorming about different ideas we could explore.

The real trick is going to be threading a needle between letting users know that the package exists and how to get to it, without being obnoxious and annoying users who know about it but don't choose to use it.

/cc @annthurium 
/cc @simurai 
/cc @sguthals

**Comment by annthurium** [comment]
thanks for starting this conversation, @smashwilson !  

The first step is knowing what our baseline usage numbers are, which will happen in the next release.

The next step would be to instrument all these entry points separately, so we can see where users are actually coming from.

Wacky idea: since this is essentially a growth problem, we could do an a/b experiment.  For example, randomly but deterministically put UUIDs into 2 buckets in a way that's repeatable. That way we can try showing the GitHub package more aggressively, but have a control for "are we annoying our users too much."  Might be more work than it's worth, just putting it out there as an idea.

it would also be GREAT to do some UXR around the discoverability of this feature.  We should definitely do that.

I would include marketing / developer education here as well.  For example, having a video on one of our educational channels to explain how to use the GitHub package would be a great first step.  While it's harder to measure how much that kind of thing impacts your actual numbers (you can't exactly use a utm referrer, lol) it seems to be a piece of the puzzle that's currently missing.  

...maybe I'm biased because I was an Atom user for years, and I didn't even know about the Git / GitHub integrations before I started working here.

**Comment by smashwilson** [comment]
> Wacky idea: since this is essentially a growth problem, we could do an a/b experiment. For example, randomly but deterministically put UUIDs into 2 buckets in a way that's repeatable.

This would be really cool 😄 

We could also likely use this as an excuse to introduce the infrastructure for feature flags while we're at it - the flag's default value would just be determined by your bucket rather than whatever other controls we want to have 🤔 

> it would also be GREAT to do some UXR around the discoverability of this feature. We should definitely do that.

👍 @sguthals was just talking with me about putting the wheels in motion here. I'd guess that discoverability would be one of the first results we'd get out of that.

**Comment by simurai** [comment]
Some more random ideas:

## Status-bar

1. Change the status-bar tile from `2 files` to `Git (2)`.
    ![image](https://user-images.githubusercontent.com/378023/42552572-f4fc1fae-8517-11e8-9eae-f559228c7c2f.png)
2. Also have a `GitHub` status-bar tile.
    ![image](https://user-images.githubusercontent.com/378023/42552926-91bdb842-8519-11e8-9fe2-9bf10c986f35.png)

## Tool-bar

Since the status-bar could get crowded, have more a tool/nav bar:

- Bundle [tool-bar](https://atom.io/packages/tool-bar) or implement something similar.
- Implement the [Persistent Controls for Docks](https://github.com/atom/atom/issues/16116) proposal.

This is much bigger in scope also more Atom's responsibility. Atom IDE and other packages would also benefit.

## Onboarding

@donokuda also mentioned that there could be some sort of "onboarding". For example an occasional "hey, you're using Git in your project but haven't used the Git tab yet... just a friendly reminder, in case you didn't know". But yeah, hard to find a balance between being useful vs annoying.

## SEO

There is a [documentation](https://flight-manual.atom.io/using-atom/sections/github-package/) and a [product page](https://github.atom.io/) with videos, but for some reason, when searching on Google for something like `how to commit in atom`, both don't show up on the first results page. Your case might be different?

Some re-wording and cross-linking might help.

## Marketing

Atom's release tweets already include the GitHub package, but there could still be the occasional promo tweet. Maybe packaged as "Pro tip", like "Forgot to commit something? You can amend by right-clicking on the last commit. + gif". Or retweet other people's tweets. On the other hand, we have been very light tweeters. Not sure if we want to change that.

> Soon, thanks to @annthurium, we'll have access to metrics that we can use to validate this hypothesis, and measure the impact of any changes that we make to improve this

👍 Agreed to wait until we have some numbers first. A/B also sounds fancy.

**Comment by annthurium** [comment]
@simurai that is an *excellent* point about SEO.

I worked on SEO at Pinterest for awhile, so doing a SEO audit of our documentation is totally something I'd be happy to handle.  Especially since a lot of SEO improvements end up improving accessibility too!

**Comment by annthurium** [comment]
Okay so, based on the user research we've been conducting, I feel good about the icon changes.  Going to close this out for now, but we can open additional issues for discoverability improvements as things come up.
