### ISSUE TITLE
Make name and discription clearer

### ISSUE THREAD

**Issue by LunarTwilight** [atom/github#1696]
The name and discription of the package makes it sound like its a package for just github intergration, not git and/or github intergration, so could it be changed?

**Comment by rsese** [comment]
Thanks for reaching out!  I can see how the description could be more explicit :+1:  Though we can't make any promises, I've shared your suggestion with the maintainers.  Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. 

Thanks again!
