### ISSUE TITLE
Hide GitHub in status bar when not relevant

### ISSUE THREAD

**Issue by withinfocus** [atom/github#1815]
### Description

As of Atom 1.33.0 and #1704 a large GitHub branding is now present in the status bar. While one could argue that the Git controls are relevant at any time in the Atom editor since a user may wish to initialize a repository there, no such origination ability is present in the GitHub component. The user of this plugin may be left with the feeling that this is merely brand placement without utility. GitHub functionality should only be shown once the context of a working Git repository -- or even further, a github.com repository -- is established.

### Steps to Reproduce

1. Install `atom/github` plugin.
2. Launch Atom, note GitHub branding all the time.

**Expected behavior:**

Only a Git component in the status bar.

**Actual behavior:**

Both Git and GitHub components in the status bar.

**Reproduces how often:**

100% of the time when the plugin is enabled.

### Versions

v1.33.0, independent of OS.

### Additional Information

![image](https://user-images.githubusercontent.com/1046132/49242031-9057ee00-f3d7-11e8-878b-622387e71c27.png)

**Comment by nudefireninja** [comment]
I agree, and the Github tab shows up next to the Git tab by default anyway, so discoverability is not an issue. I don't use Github and this new status bar button feels like wasted space and clutter to me.

**Comment by pbarbiero** [comment]
I also would prefer if I could just turn it off entirely -- the `git` one is very useful to me, but I have no desire to log into github and use it inside of atom, this ends up just being a permanent clutter to me.

**Comment by JonnyB247** [comment]
Same here. I dislike being subjected to continuous advertisement.

**Comment by robertrossmann** [comment]
If you really want to get rid of the status bar item completely all you have to do is open your stylesheet and use the following:

```less
// styles.less
.status-bar {
  .github-StatusBarTile {
    display: none;
  }
}
```

... aaand it's gone. 🎉

**Comment by pbarbiero** [comment]
That gets the result, but does not address the concern

**Comment by annthurium** [comment]
Sorry to hear about your frustrations.  

We added this button to the status bar because we've been working to add more GitHub integration features in the past few months.   We are also working to make the inclusion of the GitHub status bar widget relevant in more situations.  A lot of users who might want to use these GitHub integration features don’t know they exist, so we’re experimenting with ways to improve discoverability.

The goal was not to show GitHub’s branding, the goal is to be useful to our users by helping them discover new functionality.

Those of you who find it disruptive may hide it with the stylesheet workaround mentioned above.
