### ISSUE TITLE
Merge conflict pane keeps opening itself

### ISSUE THREAD

**Issue by brendanfalkowski** [atom/github#1816]
### Description

There's a merge conflict in my branch. Atom desperately wants me to use the merge conlfict panel, and keeps re-opening it after I close the panel.

### Steps to Reproduce

1. Have a merge conflict
2. Open some files 
3. Close the merge panel
4. Save some files

**Expected behavior:**

Merge panel stays closed.

**Actual behavior:**

Merge panel re-opens itself whenever I save a file. This constantly gets in the way.

**Reproduces how often:**

100%

### Versions

Atom 1.33.0 x 64
Mac 10.13.6

### Additional Information

I prefer to keep Atom focused on code, and I need the screen space that panel keeps taking to see code.

I use Tower App for taking Git actions.

**Comment by annthurium** [comment]
hi @brendanfalkowski -- thanks for reporting.  I can see how that's frustrating.

We're experimenting with ways of making the git functionality within Atom more discoverable, because a lot of users don't know about these features and could potentially find them useful.  However, we don't want to annoy our users, so I'l consider adding some kind of guard against this kind of behavior where the merge conflict panel opens repeatedly even after it's been closed.

In the meantime, if you don't want to use any of the Git functionality in Atom, you can disable the package "github" within your atom settings and that should stop the merge conflict panel from popping open.  

<img width="738" alt="screen shot 2018-11-29 at 4 01 03 pm" src="https://user-images.githubusercontent.com/3781742/49259901-06684f00-f3f0-11e8-9e6e-3ffaf63c4517.png">

**Comment by brendanfalkowski** [comment]
@annthurium Thanks for the write-up!

I'd like to keep the GitHub package enabled because I do use the branch indicator/switcher.

It makes sense to open the conflict panel when conflicts are detected, and I did try it out the first time it appeared (it's nice). Keeping it hidden after it's manually hidden would be perfect.
