### ISSUE TITLE
unable to log into my actual account on atom

### ISSUE THREAD

**Issue by Bilotkach** [atom/github#1821]
i had my partner for a project log into atom on my machine (school computer so using command prompt or windows credentials manager is out of the question) and now im always logged in on his account in school regardless of which PC im on how do i log out.

i also cannot do things like revoke teletype because i cannot access their actual account

**Comment by smashwilson** [comment]
It's kind of hidden, but if you open the command palette and run `GitHub: Logout` it'll forget the token you've provided on the GitHub tab and you should be prompted to re-authenticate.

Things get trickier if git itself is remembering a password for an https remote or an SSH key, because we're relying on git's internal credential-remembering system... especially given this constraint:

> (school computer so using command prompt or windows credentials manager is out of the question)

If `GitHub: Logout` doesn't let you push as the correct user, re-open and let me know and I'll try to come up with some JavaScript you can run in the developer tools to work around this :wink:

**Comment by Bilotkach** [comment]
HI, thank you for your help but unfortunately it does not log me out of my
partners account, i found that installing atom using the same atom setup
will also leave me logged into his, so im currently using a setup where i
am the logged in user

**Comment by smashwilson** [comment]
> i found that installing atom using the same atom setup
> will also leave me logged into his

Yeah - both we and git store credentials, including the authenticated account, using the OS credential manager. As a result, re-installing Atom or messing with your configuration won't help.

>  so im currently using a setup where i
> am the logged in user

Does this mean that you found a way to authenticate as yourself... ?

**Comment by smashwilson** [comment]
Oh! One easy way to do this might be to have your partner change their password (or revoke their access token if they use 2FA) on their GitHub account. Then your pushes should fail and nudge git into asking you to log in again.
