### ISSUE TITLE
Atom hanging sometimes

### ISSUE THREAD

**Issue by wohlben** [atom/github#1864]
## related issues
https://github.com/atom/atom/issues/18114
https://github.com/atom/atom/issues/18620

### Description

So, I've infrequently ran into the same issue over the last few month.
Its been extremely frequent in the last few days, however. 
normally, it happened only for ~30 minutes and then went away again for days/weeks.
The last few days its however become to frequent that I've pretty much dropped atom entirely.
Sadly, I'm unsure how exactly it happens, I can only say how atom behaves if the bug got triggered.
 
Atom becomes almost entirely unusable, things like opening new files or saving them don't actually do anything anymore.
The interface itself keeps working... you can go into the settings, switch between open tabs and similar just fine.

as I mentioned in on of the related issues
> checking if the bug got triggered is easy as well: just open the github panel ctrl-shift-8 or crl-shift-P and search for "Toggle Github Tab". If its a Spinner, you'll have to restart and might lose everything that hasn't been saved yet.

safe-mode and deleting ~/.atom entirely has no effect on the bug

### Steps to Reproduce
... I was sadly unable to really find out what triggers the bug
It might be an unexpected answer from the GitHub API or similar, as when it does happen, it keeps happening even if you restart the editor.

I can however say with certainty that the bug never happens, if atom is started without internet access (the unshare command in the linked issue)

It also doesn't happen if you disable the github package in atom.

**Expected behavior:**
atom should be useable

**Actual behavior:**
atom won't save files or open new ones for example 

**Reproduces how often:**
directly after starting whenever you're in a time frame for this bug to happen.

### Versions
I encountered the bug at work on a windows 10 install and on my personal machine with Fedora 28
As it got extremely bad over the holidays i've actually attempted to downgrade back to 1.29.0 (and each version between) and encountered it in all.

**Comment by rsese** [comment]
Thanks @wohlben - it doesn't seem like you mentioned in those other issues so just for completeness, can you confirm that you can reproduce in safe mode as well?  Also, are you working on the same project when you see this behavior or have you seen this behavior on different projects?

When the problem starts, you mentioned that the interface still works - have you checked if there are any errors in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?

**Comment by wohlben** [comment]
yes
> safe-mode and deleting ~/.atom entirely has no effect on the bug

sadly, it's really hard to reliably reproduce...
There is nothing in the devtools if it gets triggered.
 I meant that its possible to switch between already opened windows and the Window Manager (neither Windows nor i3wm at home) detects that the application is unresponsive. It just keeps running until you quit.
regular quitting is also possible if you click "don't save".

I've even tried to remove all remotes from one repository and still encountered the bug...
and my work repositories don't have any github remotes... that makes it even stranger to me

**Comment by wohlben** [comment]
Is the label 'more-information-needed' something I can provide @rsese?

or is this a general label because its impossible to debug with the current report?

**Comment by schooft** [comment]
I had the same issue for the first time. I couldn't open or save files while there was an endless spinner in the GitHub tab. Neither `atom --safe .` nor `atom --clear-window-state` helped. Only one project was affected, other simultaneously open instances worked fine.

In my case, I had a non-existing remote in `.git/config`. Deleting the corresponding lines and restarting atom resolved the issue. After putting the wrong remote back, the issue reappeared almost immediately.

Steps to reproduce:
```
mkdir test
cd test
touch test.txt
git init
echo "[remote \"origin\"]
    url = git@github.com:foo/bar.git
    fetch = +refs/heads/*:refs/remotes/origin/*" >> .git/config
atom .
```
After a few edits/saves the issue appears.

Versions:
Atom 1.34.0 on Debian 9

**Comment by rsese** [comment]
Thanks @schooft - I gave your repro steps a try but was unable to reproduce with 1.34.0 on Ubutnu 18.04.  Did you use a [supported installation method}(https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt)?  Also, are there any [devtools console errors](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?

**Comment by schooft** [comment]
I did install atom via `sudo dpkg -i atom-amd64.deb`. There is no output on the devtools console. 

Unfortunately, the non-existing remote was a red herring and I could now observe the issue with a valid remote as well. 

Instead, in my case the issue seems to be related to the Gnome keyring (seahorse). Normally, when starting atom while the keyring is locked, I am prompted for my password and the issue does not occur (the GitHub tab shows a "Login" button instead of the spinner). But in my tests that reproduced the issue, I was not asked to unlock the keyring. The password prompt did not even appear when I tried to unlock the keyring within seahorse (I was still able to unlock other keyrings, just not the one named "Login"). After a restart, I am asked for my password every time when the keyring is locked and I cannot reproduce the issue anymore. 

I do not use the Gnome keyring and the only atom-related entry in my keyring is an atom-teletype oauth-token, which I also don't need. Is there a way to tell atom not to use the keyring?

**Comment by wohlben** [comment]
it also occurs with no remote in the repository... sadly, i still have no clue  what actually causes it - nor do i have any ideas left to explorer to debug.

There is only one thing that is persistent:
unsharing the network or disabling the github extension stops the issue from ever popping up.

**Comment by Asharas** [comment]
This is still a problem as of today.  
In my case simply switching from file to file with a single click does trigger the bug with consistency.  
Unfortunately I stumble upon the same problem as wohlben, can't find error log anywhere.  

This is quite annoying especially since github is a default package and usefull.
