### ISSUE TITLE
In staging view, text gets highlighted instead of lines

### ISSUE THREAD

**Issue by LemonsArePeopleToo** [atom/github#1907]
When I click and drag to select multiple lines in the staging view, only the text I dragged over is highlighted (as if I'm just highlighting the text in a normal editor).

In the past, selected lines were slightly darker and the blue highlighting effect was never shown. I've briefly tried to tinker with CSS to fix this behaviour but honestly, familiarising myself with Atom's internals enough to manage this just isn't worth the time so I'm posting a thing here.

I was previously using **v0.22.2** in Atom 1.33.1 and it was fine. This started with the upgrade to **v0.23.3** in Atom 1.34.0. I've not tested v0.24.0 because, again, I want to write my code, I don't want to have to figure out how to make Atom load a different version of a bundled plugin without crashing repeatedly on launch (but also, v0.23.3 is newer on the releases page). This is happening on **Windows 10** and I've not tested any other operating systems.

Here's an image of an example of it happening:

![image](https://user-images.githubusercontent.com/46637718/51080268-2c139400-16d0-11e9-9548-6496be77de82.png)

For reference, here's a screenshot of the same hunk in Atom 1.33.1. I did exactly the same thing here, dragging from the same start point to the same end point with my mouse.

![image](https://user-images.githubusercontent.com/46637718/51080354-0c7d6b00-16d2-11e9-8bab-64637c7c5021.png)

(I also prefer pretty much everything about the old UI's appearance, it overall looks a lot better with the tinted text colour as well as the border lines, but that's just personal preference and isn't a big deal. It'd be nice to have an option to use the old UI while the new UI isn't as polished though? Just a thought!)

**Comment by smashwilson** [comment]
This is intentional! The diff view that just landed in stable lets you do things like copy and paste text, and (ultimately) will let us do things like diff editing. To support that, we needed to provide some way to distinguish between the character-level editor selections (which will populate the copy-paste buffer, can contain any character ranges) from the line-level diff selection (which will generate the stage or unstage patch, and can only contain whole lines that are added or removed). The styles you're seeing are the way we found to accomplish that.

Here's the `styles.less` snippet you can use to make the editor selection never visible:

```css
.github-FilePatchView atom-text-editor .selection .region,
.github-FilePatchView:focus-within atom-text-editor .selection .region {
  background-color: transparent;
}
```
