### ISSUE TITLE
Respect `core.commentChar` when stripping out comments from commit messages

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1909]
As follow-on to #1902, @smashwilson pointed out that it would be good if we respected git's `commentChar` setting. 

https://git-scm.com/docs/git-config#git-config-corecommentChar

**Comment by Sidnioulz** [comment]
Hi,

I'd like to follow up on that, and say that #1500 fixed issue #962, and that since roughly two weeks 962 occurs again. It appears likely that #1902 is responsible for that regression.

In my company we use Redmine, and our Git repository is linked to directly map #1234 to issue 1234 on Redmine. A bit like, err, how Github parse issue ids with a #. By convention we prefix each commit with a ticket number. So, this regression is forcing me to commit outside of Atom once again.
