### ISSUE TITLE
Investigate dependabot 

### ISSUE THREAD

**Issue by annthurium** [atom/github#2011]
Dependabot automatically resolves conflicts, which greenkeeper does not.  @shiftkey moved a lot of things over.  Talk to him, make a call on if this is something we want to do.

**Comment by Arcanemagus** [comment]
I've been moving things over to [Renovate](https://renovatebot.com/) from Greenkeeper myself. I don't have a lot of experience with Dependabot but from what I've seen so far the things that I like about Renovate over Dependabot are:

* Grouped PRs
  * Monorepos are usually automatically grouped (e.g. all `react` stuff together)
  * Custom groups can be defined (e.g. `eslint` + `eslint-*` stuff)
* The same PR keeps getting updated
  * Dependabot closes PRs and creates new ones when it finds an update

Some things that I like about Dependabot over Renovate:
* The compatibility badge is a nice touch, but I'm not sure how useful it actually is
* Their dashboard seems to be more fully featured than Renovate's since it supports commands there?

Things they both do better than Greenkeeper:
* First class support for lock files (in the same commit as the package update)
* Dashboards with status views into what they are actually doing instead of just having to wonder what is wrong with Greenkeeper
* PR titles that show the version number
  * This was one of the silliest changes they made, it _used_ to work this way before 🤦‍♂️

**Comment by shiftkey** [comment]
The only thing I'm missing from Dependabot is the ability to restrict it to upgrade certain dependencies, but I think that's possible via config - https://github.com/dependabot/feedback/issues/70#issuecomment-449377695 has the details, but I've not looked at using this in any of the projects I maintain. 

Happy to chat more about what we've done over on the Desktop org about this - DMs or calendar requests are fine.

**Comment by vanessayuenn** [comment]
dependabot has been officially turned on and configured for this repo 🎉
