### ISSUE TITLE
Github package crashes

### ISSUE THREAD

**Issue by vramana** [atom/github#2207]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Open atom editor 
2. Github package shows the current branch status in status bar
3. After a couple of seconds it crashes.

**Expected behavior:**

**Actual behavior:** Github package should not crash

**Reproduces how often:** I can reproduce it consistently with this repo. But not with some other repos. This repo is private repo so I can't point you at it.

This is the error message that I see in DevTools. 
 
![image](https://user-images.githubusercontent.com/3112509/61262214-19bf0380-a7a2-11e9-9e19-c61458d6fdd3.png)

### Versions

Atom    : 1.39.0-beta3
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

### Additional Information

I can provide any information that you need. I can jump in video call and let you figure out the problem.

**Comment by smashwilson** [comment]
From the stack trace, my current hunch is that this is caused by the presence of a "large" (>800 line) file patch on a pull request associated with the HEAD branch of your repository with a review comment on it. That would trigger the deferred parsing logic during patch construction and break review comment positioning in the way that you're observing.

The good news is that #2195 should already fix this, because I hit an identical error while I was developing test cases for that work :smile:

**Comment by vramana** [comment]
@smashwilson Nice. I saw the PR thought this might be good time to post the issue. Looking forward to using github on atom again.

**Comment by vramana** [comment]
Does not seem to crash anymore.
