### ISSUE TITLE
Atom Doesn't Remember Which File Was Last Edited When Working With A Single File

### ISSUE THREAD

**Issue by JosephTLyons** [atom/github#2253]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Typically, if you are working on a session and then close Atom, then reopen Atom, that session will reopen where you left off.  [Back in Atom 1.36.0, we got the feature to not open the entire parent directory if only opening a single file to edit.](https://github.com/atom/atom/pull/18608)  If you open a single file in Atom, close Atom, and reopen Atom, it will open up to the default "landing page," entirely forgetting the file you last worked on.  This happens in safe mode as well.  

### Steps to Reproduce

1. Open a single file in Atom: `atom filename.ext --safe`
2. Close atom
3. Open Atom without specifying a file: `atom --safe`
4. Notice that Atom does not remember the single file you worked on like it does when opening a directory.

**Expected behavior:**

I expected Atom to remember the last file I worked on.

**Actual behavior:**

Atom entirely forgets the last file I was working on (if it is a single file and not a directory).

**Reproduces how often:**

It reproduces for me each time I edit a single file and close, then reopen Atom.

### Additional Information

Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
npm: 6.9.0

**Comment by JosephTLyons** [comment]
Well that is strange, I added text to all the appropriate fields.  I will fix this, hang tight.

**Comment by rsese** [comment]
Thanks @JosephTLyons :+1:

This is being tracked at https://github.com/atom/settings-view/issues/1129 so you can subscribe there for updates.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
