### ISSUE TITLE
git hub panel not visible v1.40.1 

### ISSUE THREAD

**Issue by foluabajingin** [atom/github#2301]
Atom git hub panel not visible v1.40.1 l ikr ky judt won't appear the options are there. I press Cntrl 9. but it just won't work. tried cntrl 8 but that just opened the local repository. so I have no choice but to uninstall it again for a 3rd time. 

Maybe 4th times the charm lool

**Comment by wadethestealth** [comment]
When the github panel isn't visible that may mean there was a bug in the code, and most likely installing it again for a 4th time wont change anything.

Things you should try:
1. Looking in the console for errors (`Ctrl` + `Shift` + `I`) and opening an issue with the stack trace.
2. Refreshing you atom window (`Ctrl` + `Shift` + `F5`)
3. If everything continues failing write the steps you are following exactly. Things like what your git remotes look like, what remote did you last use with the package, and UI or atom command you are using. Make sure these are in order as their order might relate to the bug. It could also be helpful to know what OS you are running and if your package is up to date.

Regardless, while it may be frustrating your package isn't working, your issue is not going to help the situation.

I would either edit this with some of the steps above or close this issue.

**Comment by foluabajingin** [comment]
[atom not working.txt](https://github.com/atom/github/files/3706452/atom.not.working.txt)

I tried t download and redownload it and was given this error

**Comment by wadethestealth** [comment]
This log can not be right? This is a log for GitHub desktop, which is a completely different app. Atom is a code editor and has atom/github built in, but it can be uninstalled and reinstalled, which is why I was confused. You need to open an issue over there (https://github.com/desktop/desktop).

**Comment by wadethestealth** [comment]
This log can not be right? This is a log for GitHub desktop, which is a completely different app. Atom is a code editor and has atom/github built in, but it can be uninstalled and reinstalled, which is why I was confused. You need to open an issue over there (https://github.com/desktop/desktop).

**Comment by wadethestealth** [comment]
Also you should close this issue.
