### ISSUE TITLE
My atom live-server is not working

### ISSUE THREAD

**Issue by Harrisj22412** [atom/github#2470]
I'm new to atom, every time I try to use atom live server I receive an error message and I was curious on how to use atom-live-server? And is there any other servers that's better than atom-live server?

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
