### ISSUE TITLE
Show stagedness status in the editor gutter

### ISSUE THREAD

**Issue by joshaber** [atom/github#45]

**Comment by lgeiger** [comment]
> As far as implementation goes, I'm wondering how this would actually work. Would we essentially re-implement git-diff and suppress its styling?

I have a WIP implementation of the `git-diff` functionality inside `atom/github` using the git-shellout-strategy.
This was primarily done to investigate new possibilities of improving the performance of `git-diff` when using network mounted volumes (e.g. using sshfs). Since `git-diff` relies on synchronous git calls, Atom is almost unusable with git repos mounted over WIFI.
But this approach would also allow a fairly easy way of adding stagedness status in the editor gutter.
@joshaber Are you interested in a PR illustrating this approach in more detail?

**Comment by simurai** [comment]
> @joshaber Are you interested in a PR illustrating this approach in more detail?

FYI @joshaber isn't on this team anymore. 😢 

/cc @kuychaco @smashwilson

**Comment by lgeiger** [comment]
The code is located [here](https://github.com/atom/github/compare/master...lgeiger:git-diff?expand=1). I'm happy to flesh this out a bit more and make a PR that explains it in detail if there is general interest in this approach.

**Comment by annthurium** [comment]
we have the git diff package that has this functionality now - going to close this out.
