### ISSUE TITLE
git integration doesn't work in file tree if .git/ not in top level

### ISSUE THREAD

**Issue by wjwwood** [atom/github#778]
### Description

If you open a git repository in atom you get various git integrations, like colors to indicate new files or changed files. However, if the git repository is in a subfolder of the folder opened in atom, then these integrations do not work.

My question is, will this still be the case for this for the git/GitHub integrations present in this atom package?

I built atom from source (`1.18.0-dev-b478f19`), and my initial observations are that this case is still not supported.

This has been previously been discussed here (without the context of new GitHub integrations): https://github.com/atom/atom/issues/2203

Is there any awareness of this issue for this project? If not, is there something people in the community can do to improve this use case in this plugin?

### Steps to Reproduce

1. Open a git repository in atom and observe that git and GitHub integrations are working, e.g.:

![screen shot 2017-05-10 at 2 12 19 pm](https://cloud.githubusercontent.com/assets/100427/25921567/c34df9b0-358a-11e7-86d7-d6cb0c92006d.png)

2. Open the folder containing that repository in atom and observe that the git and GitHub integrations are not working, e.g.:

![screen shot 2017-05-10 at 2 12 40 pm](https://cloud.githubusercontent.com/assets/100427/25921577/cc7e269a-358a-11e7-9578-c32264e92bcd.png)

**Expected behavior:**

I would expect that git (and GitHub) integrations in the treeview and in the gutter for files would work regardless of whether or not the root of the git repository is a top-level folder in the project.

**Actual behavior:**

Git (and GitHub) integrations only work when the root of the git repository is a top-level project folder.

**Reproduces how often:**

Always.

### Versions

```
% atom --version
Atom    : 1.18.0-dev-b478f19
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
% apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.9.0
```

I am on macOS `10.11.6` "El Capitan".

**Comment by BinaryMuse** [comment]
Thanks for the detailed issue.

This package works like the core Atom integration — namely, it will work if the top-level project is a *subfolder* of a Git repository (as show here, where I have opened Atom's `src` folder):

<img width="1026" alt="cursor_and_staged_changes__src_crash-reporter-start_js_ ___github_atom_src_and_about_blank" src="https://cloud.githubusercontent.com/assets/189606/25922781/b7e23564-35da-11e7-81b1-a9c9b3187ebf.png">

but it will not work if you have a super-folder open that is not itself a repo. This is largely because the package is based largely on Atom's built-in `Project` API, the same one that powers the other Git integrations.

I would personally not be opposed to changing this behavior, as long as it matches Atom core's behavior — but there are intricacies to consider, such as, should we even present an "initialize a repo" dialog for a super-folder if it has `.git` children, grandchildren, etc.?

That said, we won't change the behavior here until such a time that core is updated, so I'm going to close this issue. We'll certainly be keeping an eye on atom/atom#2203 and will follow suit if anything changes on that front.

**Comment by wjwwood** [comment]
Sounds good. I just wanted to make sure the developers here were aware of the potentially different UI mode in that scenario (like the initialize Git repo pane question you posed). Thanks for the response.

**Comment by wjwwood** [comment]
Additional cross-reference: https://github.com/atom/atom/issues/5728

**Comment by JosephTLyons** [comment]
+1.  Really throws me off when this happens.
