### ISSUE TITLE
directory of git worktree is not working

### ISSUE THREAD

**Issue by muukii** [atom/github#811]
**Reproduces how often:**

100% 

### Versions

```
Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.12.2

OSX 10.12.3, 2017 MBP.
```

**Comment by rsese** [comment]
Thanks for the report!  In addition to completely filling out the issue template, I think similarly to https://github.com/atom/github/issues/778, this behavior matches the behavior of core Atom and there's an enhancement request to support git worktrees at https://github.com/atom/atom/issues/8168.  

Going to go ahead and close like you did for https://github.com/atom/github/issues/778 @BinaryMuse but let me know if you think this is a bit different :v:

---

Thanks for reaching out!

We require the template to be completely filled out on all new issues and pull requests. In particular, more details about steps to reproduce, screenshots, etc. would be helpful.

We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
