### ISSUE TITLE
Larger commit message editor

### ISSUE THREAD

**Issue by dflock** [atom/github#818]
### Description

The commit message editor is currently (vertically) very small - and not resizable. It would be a much better experience if some or all of these were true:

* The commit message editor was vertically resizable
* You could pop open the commit message in a new pane/tab/something

### Versions

```console
$ apm-beta --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.13.0

$ atom-beta --version
Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
```

**Comment by simurai** [comment]
> You could pop open the commit message in a new pane/tab/something

👍  Good suggestion.

Next to a keybinding/context-menu, there could be an :arrow_heading_up: expand button when you hover the bottom right corner of the input? Clicking it would open a new pane with the `.git/COMMIT_EDITMSG` that could be edited. And also has the Git Commit Message grammar.

![screen shot 2017-05-17 at 4 03 55 pm](https://cloud.githubusercontent.com/assets/378023/26142544/f6fb3412-3b1b-11e7-8163-5a06a5373fef.png)

**Comment by smashwilson** [comment]
I like the idea of popping out into a Pane, yeah. Should we hide the mini-editor while the pane editor is open?

**Comment by BinaryMuse** [comment]
I love this idea. It would also allow us to support message templates more easily, since the editor buffer would read directly from the file. (Side node: maybe we should be watching this file anyway and updating the message box when it changes?)

If the user has the file expanded, I'd love to gray out the box or display a little overlay with an informational message. If the user clicks it (or the arrow or something) again, it'd find and focus that buffer in the workspace center. Then if the editor is closed, we re-read the text and turn it back on.
