### ISSUE TITLE
Make expected error cases friendlier such as pulling with merge conflicts

### ISSUE THREAD

**Issue by Haacked** [atom/github#821]
I tried to pull a branch from github.com into my local repo with Atom. There were some merge conflicts.

The error message I got was:

```
From https://github.com/Haacked/todo-app
 * branch            haacked-tries-to-code -> FETCH_HEAD
   4234f31..808d71d  haacked-tries-to-code -> origin/haacked-tries-to-code
```

It was reported using the standard red error message box. It made me feel like I made a mistake or that I broke Atom.

Since pulling branches with conflicts is an expected use case, we should provide a friendlier message about what just happened and perhaps a link to more documentation on resolving merge conflicts.

**Comment by kuychaco** [comment]
Very good point

**Comment by kuychaco** [comment]
So I started implementing a fix for this that involves using a warning notification rather than an error notification. Here's what it looks like:

![pull-merge-conflicts](https://cloud.githubusercontent.com/assets/7910250/26495914/ca92fa66-4225-11e7-92ed-72291ca900ff.gif)

I'm thinking that a notification might not even be helpful, and that it might be more of an annoyance. In my opinion it's pretty clear what's happening based on the fact that merge conflicts appear and the commit box is populated with a message:

```
Merge branch 'master' of https://github.com/owner/repo

# Conflicts:
#	file.txt
```

So I'm thinking of simply removing the notification to address the concerns brought up in this issue. @Haacked what do you think?

**Comment by Haacked** [comment]
I agree. The notification gets in the way. The "Merge Conflicts" list
showing up is notice enough.
