### ISSUE TITLE
Any Plans on Integrating Git Graphs

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom/github#823]
Git graphs like those introduced by [Git Log](https://github.com/nikhilkalige/git-log) are quite useful for checking the collaboration flow of projects, which is what atom lacks for a long time.

Unfortunately, `Git Log` hasn't been maintained for a long while now and probably already deprecated. Just wondering if there is any chance this package will take it over, considering this is part of the git feature. Thanks.

![image](https://cloud.githubusercontent.com/assets/17170199/26132365/341e7bc6-3ae3-11e7-870e-996b7dd676f9.png)

**Comment by BinaryMuse** [comment]
Thanks for the feedback!

Something like this isn't on our [Short-Term Roadmap](https://github.com/atom/github/projects/8), but introspection into the repository's history is certainly something we'd like to consider at some point.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after noting the information to keep our backlog clean and focused. Thanks again!
