### ISSUE TITLE
Auto hide the right pane

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/github#824]
Is there any way to auto hide the right pane by default ??

**Comment by ungb** [comment]
You can also just click on the arrow to have it hide.  

![image](https://cloud.githubusercontent.com/assets/5624870/26132900/43d4c484-3a58-11e7-9698-6cf168330eba.png)


if you mean on startup, you can add the following to your init.coffee script

```
if (atom.workspace.getRightDock().state.visible)
  atom.commands.dispatch(atom.views.getView(atom.workspace.getRightDock()), 'window:toggle-right-dock');
```


In the future, please following the issue template.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by ooJerryLeeoo** [comment]
@ungb Thanks, `if (document.readyState && atom.workspace.getRightDock().state.visible)
  atom.commands.dispatch(atom.views.getView(atom.workspace.getRightDock()), 'window:toggle-right-dock');` solved my problem :+1:

**Comment by dirk-thomas** [comment]
After installing the latest version of the `github` package (0.1.2) the dock is not shown by default anymore for me.

**Comment by dirk-thomas** [comment]
After installing the latest version of the `github` package (0.1.2) the dock is not shown by default anymore for me. I closed all instances, opened one new instance, hide the dock, close the instance again. Now new instances seem to consistently open without the dock being visible.
