### ISSUE TITLE
UX: can not interact with the panes when opening a file via advanced-open-file

### ISSUE THREAD

**Issue by hobofan** [atom/github#825]
### Description

I opened a file the way I normally would (via `advanced-open-file`, in a repository that contains unstaged changes. Those changes show up in the Git pane, but when trying to click anywhere in the Git (or Github) pane, the file looses focus and the Git pane displays the "Initialize a new project..." text it shows when you are not in a git repo.

### Steps to Reproduce

1. Open Atom
2. Open a file in a git repo via `advanced-open-file`
3. Click inside the Git pane

**Expected behavior:**

I expected to be able to interact with the contents of the Git pane.

**Actual behavior:**

The content in the git pane vanishes when I click inside it. When I click into the pane of the file again, the content reapears (this can be repeated infinitely).

**Reproduces how often:**

With the steps above 100% of the time. During debugging I noticed that it doesn't happen if I open the file via the standard "Open..." dialog, which I wouldn't do in my normal workflow. Couldn't reproduce in safe mode since advanced-open-file wasn't present.

### Versions

`atom-beta --version`:
```
Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

`apm-beta --version`:
```
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.10.1
```

OS: macOS X 10.12.4

**Comment by smashwilson** [comment]
It looks like we regressed here when we ported to the Docks API. We infer the active git context from the active pane, but with docks, the active pane can be in one of four places... and include things like the git or GitHub tabs. I've made it explicitly fall back to the active pane in the center, and made it so that the git and GitHub tabs report their own contexts so that you can never change context by activating them (which would always be confusing).

Thanks for the report! The fix will be in the next hotfix release we do 🙇
