### ISSUE TITLE
UX: Pinning repo feature is a somewhat confusing concept

### ISSUE THREAD

**Issue by PandelisZ** [atom/github#830]
### Description

The auto pinning feature feels slightly confusing initially. I sometimes just browse through a PR and read the comments and discussions. This is a case where I wouldn't want to automatically be pinned to the PR. This default behaviour makes me feel stuck in this PR

### Steps to Reproduce

1. Click into a PR within the GitHub pane

**Expected behavior:**

Now browsing this PR and looking through discussion with the option to return to the all the PRs

Proposal to add a back button as shown below

<img width="405" alt="screen shot 2017-05-17 at 12 21 46 copy" src="https://cloud.githubusercontent.com/assets/8436717/26151882/99c64b0c-3afc-11e7-8193-16d44d8b1cc0.png">

**Actual behavior:**

User needs to click on unpin to return to the PR list

<img width="405" alt="screen shot 2017-05-17 at 12 21 46" src="https://cloud.githubusercontent.com/assets/8436717/26151907/b70f2af8-3afc-11e7-886c-90ebcf9bb979.png">

**Reproduces how often:**

Every time 100%

### Versions

github 0.0.9
atom 1.18.0-beta0
Mac OS - 10.12.3

**Comment by kuychaco** [comment]
@simurai for 💭

**Comment by simurai** [comment]
> Click into a PR within the GitHub pane

It sounds like you're seeing a list of PRs, like in this [screenshot](https://github.com/atom/github/pull/714#issuecomment-298240407). That's probably because you're on `master` branch and there isn't a PR for it. The current GitHub panel is more a "here is the PR for your **current** branch, but in case we got it wrong or a PR can't be found, you can pin another PR".

> I sometimes just browse through a PR

Yes, that is something we were thinking too. An idea is to have a search/autocomplete dropdown, see https://github.com/atom/github/pull/714#issuecomment-298145826. Or maybe once we have a list of branches, we could show which ones have a PR. And it depends if we wanna add notifications like on github.com. I usually just browse PRs if they are new or I get pinged or asked to review.

**Comment by simurai** [comment]
Here an exploration of a mini GitHub browser: https://github.com/atom/github/issues/1019

It wouldn't just be for PRs, but anything that the API allows to be searched for.

**Comment by annthurium** [comment]
we have different github package behavior now that doesn't include pinning repos.  Going to close this out.  😄
