### ISSUE TITLE
Unable to treat submodule workdir as repository root

### ISSUE THREAD

**Issue by BinaryMuse** [atom/github#839]
See https://github.com/atom/github/issues/309#issuecomment-302126199

Even when making a submodule working directory one of Atom's project roots, we still don't correctly find the submodule's `.git` folder (there's a `.git` file but it points to a folder in the parent's `.git/modules` folder), so we walk up the tree and find the parent repo instead. We need to:

1. Adjust `WorkdirCache` to account for this.
2. Fix `Repository#getGitDirectoryPath` and use it everywhere we're hardcoding a path to a `.git` folder.

**Comment by pleonex** [comment]
This issue also happens when working with the `git worktree` command [doc](https://git-scm.com/docs/git-worktree). This commands allows to have different copies of the repository in different branches but sharing the same *.git* folder, so I can avoid to do several clones and keep them update. It works like submodules, the main folder will have the actual .git folder and other folders will have a .git file that points to the actual .git folder with the `gitdir` prefix.
