### ISSUE TITLE
Pulling the tracking git branch via UI causes error

### ISSUE THREAD

**Issue by vvs** [atom/github#918]
Doing git pull via the new Atom UI (pressing the "down arrow" button in the bottom-right corner, and then pressing "Pull" button, or "Fetch" button) causes the following error:

Unable to pull
fatal: Couldn't find remote ref my-local-branch-name

Doing the 'git pull' from the command line works fine.

Please note that there is no 'my-local-branch-name' on the server indeed, the remote branch name is different, but the local branch is set to track that remote branch, let's call it "my-remote-branch".

**Reproduces how often:**

100%

### Versions
Atom : 1.18.0-beta3
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0

Let me know if you need more info (and how to get that info).

**Comment by vvs** [comment]
Some more info. Looking at the logs, I see that atom tries to perform the following command:

`git  pull origin my-local-branch-name`

Which is obviously wrong, since my-local-branch-name is a local branch.

**Comment by BinaryMuse** [comment]
Very good point — seems as though we look up the remote for the current branch, but we don't look up the upstream tracking branch as configured with the `branch.branchname.merge` (and in fact you can specify multiple values in order to have git perform an octopus merge when you pull).

/cc @kuychaco for 💭 s
