### ISSUE TITLE
Staging mode changes on macOS impossible from "Unstaged Changes" view.

### ISSUE THREAD

**Issue by phyllisstein** [atom/github#942]
### Description
:wave: Hey! I just noticed something interesting when trying to stage a file using the "Stage File" button in the "Unstaged Changes" diff view: when I change the file's mode from `644` to `755`, Atom appears to stage the changes to its contents but not the changes to the mode. Right-clicking the file and clicking "Stage" works, and clicking "Stage All" works, but the diff view leaves the file in a half-staged netherworld. `git diff` from the command line shows the unstaged mode change.

![git](https://user-images.githubusercontent.com/2207980/27232118-d3679b5c-5282-11e7-83c3-db7095b37ef4.gif)

### Steps to Reproduce

1. Create a file (e.g., `test.js`).
2. Change the file's mode from `644` to `755`.
3. Open the file in the Git package's diff view.
4. Click "Stage File."

**Expected behavior:** I would expect the whole file to be staged, including changes to its metadata.

**Actual behavior:** Only the contents of the file are staged.

**Reproduces how often:** 100% of the time.

### Versions
```
~ ❯❯❯ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

~ ❯❯❯ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.1

~ ❯❯❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```

### Additional Information
💖  Thanks for taking a look.

**Comment by BinaryMuse** [comment]
Oh this is very interesting! Thanks for the report.

If I'm not mistaken, the "Stage File" button from the diff view actually stages all the *contents* of the file, not the actual file itself (as opposed to the list in the dock). A change that makes obvious sense is to change this button so that it actually stages the whole file; the question I'm less sure about is, what should happen if you stage the last line or hunk in a file that has its mode changed? Should that be staged separately? Or is there an implicit "I'm staging the *rest of this file*" that includes the mode change?

/cc @kuychaco for 💭

**Comment by BinaryMuse** [comment]
Based on the gif there's also some weirdness about what we display when the only thing changed is the mode
